# render.yaml - CONFIRMED CORRECT VERSION

services:
  # Backend API (FastAPI / Uvicorn)
  - type: web
    name: curebot-api
    env: python
    region: oregon
    plan: free
    rootDir: health-bot
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: HUGGING_FACE_HUB_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false

  # Frontend (Vite / React) as a Static Site
  - type: static_site  # <<< THIS LINE IS THE KEY
    name: curebot-web
    region: oregon
    plan: free
    rootDir: curebot-hug-design
    buildCommand: |
      npm install
      npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: curebot-api
          property: url
