# Render Blueprint for deploying CureBot
# Docs: https://render.com/docs/blueprint-spec

# (Optional but recommended) Enable Pull Request Previews
previews: true

services:
  # -----------------------------
  # Backend API (FastAPI / Uvicorn)
  # -----------------------------
  - type: web
    name: curebot-api
    env: python
    region: oregon
    plan: free
    rootDir: health-bot
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: LLM_PROVIDER
        value: hf
      - key: HUGGING_FACE_HUB_TOKEN
        sync: false # Set this in the Render dashboard
      - key: JWT_SECRET
        sync: false # Set this in the Render dashboard
      - key: TESSERACT_CMD
        sync: false
      - key: VOSK_MODEL_DIR
        sync: false
      - key: CHROMA_DIR
        value: ./chroma

  # -------------------------------------
  # Frontend (Vite / React) as a Static Site
  # -------------------------------------
  - type: static_site  # CORRECTED: Was "static", now "static_site"
    name: curebot-web
    region: oregon
    plan: free
    rootDir: curebot-hug-design
    buildCommand: |
      npm install
      npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: curebot-api
          property: url

# -------------------------------------
# Optional: Persistent Disk Storage
# -------------------------------------
# disks:
#   - name: curebot-uploads
#     mountPath: /opt/render/project/src/health-bot/uploads
#     sizeGB: 1
#     serviceNames:
#       - curebot-api
